dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:ci
branches:
  except:
    - gh-pages
notifications:
  email: false
