-- Originally from https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2024/accessibility/lighthouse_score_by_government.sql
-- Converted for DuckDB.
WITH score_data AS (
  SELECT
    page,
    performance_score,
    accessibility_score,
    best_practices_score,
    seo_score
  FROM
  desktop_wagtail_2025
),
domain_scores AS (
  SELECT
    page,
    CASE
      -- United Nations
      WHEN regexp_matches(page, '\.un\.org/|\.worldbank\.org/|\.undp\.org/|\.reliefweb.int/|\.who.int/|\.unfccc.int/|\.unccd.int/|\.unesco.org/') THEN 'United Nations'
      WHEN regexp_matches(page, '\.europa\.eu/') THEN 'European Union'

      -- North American States and Provinces
      WHEN regexp_matches(page, '\.(alabama|al)\.gov/') THEN 'Alabama'
      WHEN regexp_matches(page, '\.(alaska|ak)\.gov/') THEN 'Alaska'
      WHEN regexp_matches(page, '\.(arizona|az)\.gov/') THEN 'Arizona'
      WHEN regexp_matches(page, '\.(arkansas|ar)\.gov/') THEN 'Arkansas'
      WHEN regexp_matches(page, '\.(california|ca)\.gov/') THEN 'California'
      WHEN regexp_matches(page, '\.(colorado|co)\.gov/') THEN 'Colorado'
      WHEN regexp_matches(page, '\.(connecticut|ct)\.gov/') THEN 'Connecticut'
      WHEN regexp_matches(page, '\.(delaware|de)\.gov/') THEN 'Delaware'
      WHEN regexp_matches(page, '\.(florida|fl)\.gov/|\.myflorida\.com/') THEN 'Florida'
      WHEN regexp_matches(page, '\.(georgia|ga)\.gov/') THEN 'Georgia State' -- To avoid confusion with the country
      WHEN regexp_matches(page, '\.(hawaii|hi|ehawaii)\.gov/') THEN 'Hawaii'
      WHEN regexp_matches(page, '\.(idaho|id)\.gov/') THEN 'Idaho'
      WHEN regexp_matches(page, '\.(illinois|il)\.gov/') THEN 'Illinois'
      WHEN regexp_matches(page, '\.(indiana|in)\.gov/') THEN 'Indiana'
      WHEN regexp_matches(page, '\.(iowa|ia)\.gov/') THEN 'Iowa'
      WHEN regexp_matches(page, '\.(kansas|ks)\.gov/') THEN 'Kansas'
      WHEN regexp_matches(page, '\.(kentucky|ky)\.gov/') THEN 'Kentucky'
      WHEN regexp_matches(page, '\.(louisiana|la)\.gov/') THEN 'Louisiana'
      WHEN regexp_matches(page, '\.(maine|me)\.gov/') THEN 'Maine'
      WHEN regexp_matches(page, '\.(maryland|md)\.gov/') THEN 'Maryland'
      WHEN regexp_matches(page, '\.(massachusetts|ma|mass)\.gov/') THEN 'Massachusetts'
      WHEN regexp_matches(page, '\.(michigan|mi)\.gov/') THEN 'Michigan'
      WHEN regexp_matches(page, '\.(minnesota|mn)\.gov/') THEN 'Minnesota'
      WHEN regexp_matches(page, '\.(mississippi|ms)\.gov/') THEN 'Mississippi'
      WHEN regexp_matches(page, '\.(missouri|mo)\.gov/') THEN 'Missouri'
      WHEN regexp_matches(page, '\.(montana|mt)\.gov/') THEN 'Montana'
      WHEN regexp_matches(page, '\.(nebraska|ne)\.gov/') THEN 'Nebraska'
      WHEN regexp_matches(page, '\.(nevada|nv)\.gov/') THEN 'Nevada'
      WHEN regexp_matches(page, '\.(newhampshire|nh)\.gov/') THEN 'New Hampshire'
      WHEN regexp_matches(page, '\.(newjersey|nj)\.gov/') THEN 'New Jersey'
      WHEN regexp_matches(page, '\.(newmexico|nm)\.gov/') THEN 'New Mexico'
      WHEN regexp_matches(page, '\.(newyork|ny)\.gov/') THEN 'New York'
      WHEN regexp_matches(page, '\.(northcarolina|nc)\.gov/') THEN 'North Carolina'
      WHEN regexp_matches(page, '\.(northdakota|nd)\.gov/') THEN 'North Dakota'
      WHEN regexp_matches(page, '\.(ohio|oh)\.gov/') THEN 'Ohio'
      WHEN regexp_matches(page, '\.(oklahoma|ok)\.gov/') THEN 'Oklahoma'
      WHEN regexp_matches(page, '\.(oregon|or)\.gov/') THEN 'Oregon'
      WHEN regexp_matches(page, '\.(pennsylvania|pa)\.gov/') THEN 'Pennsylvania'
      WHEN regexp_matches(page, '\.(rhodeisland|ri)\.gov/') THEN 'Rhode Island'
      WHEN regexp_matches(page, '\.(southcarolina|sc)\.gov/') THEN 'South Carolina'
      WHEN regexp_matches(page, '\.(southdakota|sd)\.gov/') THEN 'South Dakota'
      WHEN regexp_matches(page, '\.(tennessee|tn)\.gov/') THEN 'Tennessee'
      WHEN regexp_matches(page, '\.(texas|tx)\.gov/') THEN 'Texas'
      WHEN regexp_matches(page, '\.(utah|ut)\.gov/') THEN 'Utah'
      WHEN regexp_matches(page, '\.(vermont|vt)\.gov/') THEN 'Vermont'
      WHEN regexp_matches(page, '\.(virginia)\.gov/') THEN 'Virginia'
      WHEN regexp_matches(page, '\.(washington|wa)\.gov/') THEN 'Washington'
      WHEN regexp_matches(page, '\.(washington|wa)\.gov/') THEN 'Washington'
      WHEN regexp_matches(page, '\.(westvirginia|wv)\.gov/') THEN 'West Virginia'
      WHEN regexp_matches(page, '\.(wisconsin|wi)\.gov/') THEN 'Wisconsin'
      WHEN regexp_matches(page, '\.(wyoming|wy)\.gov/') THEN 'Wyoming'
      WHEN regexp_matches(page, '\.dc\.gov/') THEN 'DC'
      WHEN regexp_matches(page, '\.pr\.gov/') THEN 'Puerto Rico'
      WHEN regexp_matches(page, '\.guam\.gov/') THEN 'Guam'
      WHEN regexp_matches(page, '\.americansamoa\.gov/') THEN 'American Samoa'
      -- USA .gov domains need to be at the very end so that all other instances catch them.
      WHEN regexp_matches(page, '\.gob\.mx/') THEN 'Mexico'
      WHEN regexp_matches(page, '\.(gc\.ca|canada\.ca|alberta\.ca|gov\.ab\.ca|gov\.bc\.ca|manitoba\.ca|gov\.mb\.ca|gnb\.ca|gov\.nb\.ca|gov\.nl\.ca|novascotia\.ca|gov\.ns\.ca|ontario\.ca|gov\.on\.ca|gov\.pe\.ca|quebec\.ca|gouv\.qc\.ca|revenuquebec\.ca|saskatchewan\.ca|gov\.sk\.ca|gov\.nt\.ca|gov\.nu\.ca|yukon\.ca|gov\.yk\.ca)/') THEN 'Canada'

      -- European Countries
      WHEN regexp_matches(page, '\.(gov|mil)\.al/') THEN 'Albania'
      WHEN regexp_matches(page, '\.ax/') THEN 'Åland'
      WHEN regexp_matches(page, '\.(gov|mil)\.ad/|\.govern\.ad/|\.exteriors\.ad/|\.consellgeneral\.ad/') THEN 'Andorra'
      WHEN regexp_matches(page, '\.am/') THEN 'Armenia'
      WHEN regexp_matches(page, '\.gv\.at/') THEN 'Austria'
      WHEN regexp_matches(page, '\.az/') THEN 'Azerbaijan'
      WHEN regexp_matches(page, '\.eus/') THEN 'Basque Country'
      WHEN regexp_matches(page, '\.(gov|mil)\.by/') THEN 'Belarus'
      WHEN regexp_matches(page, '\.belgium\.be/|\.(gov|mil)\.be/|\.fgov\.be/|\.vlaanderen\.be/|\.wallonie\.be/|\.brussels\.be/|\.mil\.be/') THEN 'Belgium'
      WHEN regexp_matches(page, '\.ba/') THEN 'Bosnia and Herzegovina'
      WHEN regexp_matches(page, '\.government\.bg/') THEN 'Bulgaria'
      WHEN regexp_matches(page, '\.(gov|mil)\.hr/') THEN 'Croatia'
      WHEN regexp_matches(page, '\.cy/') THEN 'Cyprus'
      WHEN regexp_matches(page, '\.(gov|mil)\.cz/') THEN 'Czechia (Czech Republic)'
      WHEN regexp_matches(page, '\.(gov|mil)\.dk/|\.ft\.dk/|\.nemkonto\.dk/|\.nemlog-in\.dk/|\.mitid\.dk/|\.digst\.dk/|\.sikkerdigital\.dk/|\.forsvaret\.dk/|\.skat\.dk/|\.stps\.dk/|\.ufm\.dk/|\.urm\.dk/|\.uvm\.dk/|\.politi\.dk/|\.dataetiskraad\.dk/|\.at\.dk/|\.kum\.dk/') THEN 'Denmark'
      WHEN regexp_matches(page, '\.riik\.ee/|\.riigiteataja\.ee/|\.eesti\.ee/|\.valitsus\.ee/') THEN 'Estonia'
      WHEN regexp_matches(page, '\.(gov|mil)\.fi/|\.valtioneuvosto\.fi/|\.minedu\.fi/|\.formin\.fi/|\.intermin\.fi/|\.suomi\.fi/|\.ym\.fi/|\.stm\.fi/|\.tem\.fi/|\.lvm\.fi/|\.mmm\.fi/|\.okm\.fi/|\.vm\.fi/|\.defmin\.fi/|\.oikeusministerio\.fi/|\.um\.fi/|\.vero\.fi/|\.kela\.fi/') THEN 'Finland'
      WHEN regexp_matches(page, '\.gouv\.fr/') THEN 'France'
      WHEN regexp_matches(page, '\.(gov|mil)\.ge/') THEN 'Georgia Country'
      WHEN regexp_matches(page, '\.bund\.de/') THEN 'Germany'
      WHEN regexp_matches(page, '\.gi/') THEN 'Gibraltar'
      WHEN regexp_matches(page, '\.(gov|mil)\.gr/') THEN 'Greece'
      WHEN regexp_matches(page, '\.gov\.gl/|\.naalakkersuisut\.gl/|\.stat\.gl/|\.oqaasileriffik\.gl/|\.sullissivik\.gl/|\.sisimiut\.gl/|\.kalaallitnunaata\.gl/|\.inatsisartut\.gl/|\.politi\.gl/|\.visitgreenland\.gl/|\.energitjenesten\.gl/|\.nusuka\.gl/|\.telepost\.gl/|\.kujalleq\.gl/|\.sermersooq\.gl/|\.aviisi\.gl/|\.anjuma\.gl/|\.kni\.gl/|\.greenlandinstitute\.gl/|\.mhs\.gl/|\.iluarsartuiffik\.gl/|\.royalgroenland\.gl/|\.gux\.gl/|\.univiseyisarti\.gl/|\.arcticcommand\.gl(/|\.$)') THEN 'Greenland'
      WHEN regexp_matches(page, '\.(gov|mil)\.hu/') THEN 'Hungary'
      WHEN regexp_matches(page, '\.is/') THEN 'Iceland'
      WHEN regexp_matches(page, '\.(gov|mil)\.ie/') THEN 'Ireland'
      WHEN regexp_matches(page, '\.im/') THEN 'Isle of Man'
      WHEN regexp_matches(page, '\.(gov|mil)\.it/|\.governo\.it/') THEN 'Italy'
      WHEN regexp_matches(page, '\.kz/') THEN 'Kazakhstan'
      WHEN regexp_matches(page, '\.lv/') THEN 'Latvia'
      WHEN regexp_matches(page, '\.li/') THEN 'Liechtenstein'
      WHEN regexp_matches(page, '\.(gov|mil)\.lt/|\.vrm\.lt/|\.sam\.lt/|\.ukmin\.lt/|\.lrv\.lt/|\.uzt\.lt/|\.migracija\.lt/|\.kam\.lt/|\.lrs\.lt/|\.urm\.lt/') THEN 'Lithuania'
      WHEN regexp_matches(page, '\.public\.lu/|\.etat\.lu/') THEN 'Luxembourg'
      WHEN regexp_matches(page, '\.mt/') THEN 'Malta'
      WHEN regexp_matches(page, '\.md/') THEN 'Moldova'
      WHEN regexp_matches(page, '\.mc/') THEN 'Monaco'
      WHEN regexp_matches(page, '\.me/') THEN 'Montenegro'
      WHEN regexp_matches(page, '\.(gov|mil)\.nl/|\.overheid\.nl/|\.mijnoverheid\.nl/') THEN 'Netherlands'
      WHEN regexp_matches(page, '\.mk/') THEN 'Macedonia'
      WHEN regexp_matches(page, '\.(gov|mil)\.no/|\.regjeringen\.no/|\.stortinget\.no/|\.nav\.no/|\.helsenorge\.no/|\.udir\.no/|\.udi\.no/|\.politi\.no/|\.nve\.no/|\.ssb\.no/|\.norges-bank\.no/|\.miljodirektoratet\.no/|\.arbeidstilsynet\.no/|\.forsvaret\.no/|\.skatteetaten\.no/|\.brreg\.no/|\.vegvesen\.no/|\.mattilsynet\.no/|\.lovdata\.no/|\.altinn\.no/|\.nkom\.no/|\.fhi\.no/|\.dsa\.no/|\.kystverket\.no/|\.bufdir\.no/|\.nupi\.no(/|\.$)') THEN 'Norway'
      WHEN regexp_matches(page, '\.(gov|mil)\.pl/') THEN 'Poland'
      WHEN regexp_matches(page, '\.(gov|mil)\.pt/') THEN 'Portugal'
      WHEN regexp_matches(page, '\.ro/') THEN 'Romania'
      WHEN regexp_matches(page, '\.(gov|mil)\.ru/|\.govvrn\.ru/') THEN 'Russia'
      WHEN regexp_matches(page, '\.sm/') THEN 'San Marino'
      WHEN regexp_matches(page, '\.(gov|mil)\.rs/') THEN 'Serbia'
      WHEN regexp_matches(page, '\.(gov|mil)\.sk/') THEN 'Slovakia'
      WHEN regexp_matches(page, '\.(gov|mil)\.si/') THEN 'Slovenia'
      WHEN regexp_matches(page, '\.(gov|mil)\.es|gob\.es|ine\.es|boe\.es/') THEN 'Spain'
      WHEN regexp_matches(page, '\.sj/') THEN 'Svalbard and Jan Mayen Islands'
      WHEN regexp_matches(page, '\.(gov|mil)\.se/|\.1177\.se/|\.funktionstjanster\.se/|\.hemnet\.se/|\.smhi\.se/|\.sverigesradio\.se/|\.klart\.se/|\.bankid\.com/|\.synonymer\.se/|\.arbetsformedlingen\.se/|\.skatteverket\.se/|\.schoolsoft\.se/|\.postnord\.se/|\.grandid\.com/|\.viaplay\.se/|\.skola24\.se/|\.forsakringskassan\.se/|\.vklass\.se|sl\.se/|\.familjeliv\.se(/|\.$)') THEN 'Sweden'
      WHEN regexp_matches(page, '\.admin\.ch/') THEN 'Switzerland'
      WHEN regexp_matches(page, '\.gv\.ua/') THEN 'Ukraine'
      WHEN regexp_matches(page, '\.(gov|mil)\.uk/') THEN 'United Kingdom (UK)'

      -- Other Countries
      WHEN regexp_matches(page, '\.af/') THEN 'Afghanistan'
      WHEN regexp_matches(page, '\.dz/') THEN 'Algeria'
      WHEN regexp_matches(page, '\.as/') THEN 'American Samoa'
      WHEN regexp_matches(page, '\.ao/') THEN 'Angola'
      WHEN regexp_matches(page, '\.ai/') THEN 'Anguilla'
      WHEN regexp_matches(page, '\.aq/') THEN 'Antarctica'
      WHEN regexp_matches(page, '\.ag/') THEN 'Antigua and Barbuda'
      WHEN regexp_matches(page, '\.(mil|gov|gob|gub)\.ar/') THEN 'Argentina'
      WHEN regexp_matches(page, '\.aw/') THEN 'Aruba'
      WHEN regexp_matches(page, '\.ac/') THEN 'Ascension Island'
      WHEN regexp_matches(page, '\.au/') THEN 'Australia'
      WHEN regexp_matches(page, '\.bs/') THEN 'Bahamas'
      WHEN regexp_matches(page, '\.bh/') THEN 'Bahrain'
      WHEN regexp_matches(page, '\.bd/') THEN 'Bangladesh'
      WHEN regexp_matches(page, '\.bb/') THEN 'Barbados'
      WHEN regexp_matches(page, '\.bz/') THEN 'Belize'
      WHEN regexp_matches(page, '\.bj/') THEN 'Benin'
      WHEN regexp_matches(page, '\.bm/') THEN 'Bermuda'
      WHEN regexp_matches(page, '\.bt/') THEN 'Bhutan'
      WHEN regexp_matches(page, '\.bo/') THEN 'Bolivia'
      WHEN regexp_matches(page, '\.bq/') THEN 'Bonaire'
      WHEN regexp_matches(page, '\.bw/') THEN 'Botswana'
      WHEN regexp_matches(page, '\.bv/') THEN 'Bouvet Island'
      WHEN regexp_matches(page, '\.br/') THEN 'Brazil'
      WHEN regexp_matches(page, '\.io/') THEN 'British Indian Ocean Territory'
      WHEN regexp_matches(page, '\.vg/') THEN 'British Virgin Islands'
      WHEN regexp_matches(page, '\.bn/') THEN 'Brunei'
      WHEN regexp_matches(page, '\.bf/') THEN 'Burkina Faso'
      WHEN regexp_matches(page, '\.mm/') THEN 'Burma (officially: Myanmar)'
      WHEN regexp_matches(page, '\.bi/') THEN 'Burundi'
      WHEN regexp_matches(page, '\.kh/') THEN 'Cambodia'
      WHEN regexp_matches(page, '\.cm/') THEN 'Cameroon'
      WHEN regexp_matches(page, '\.ca/') THEN 'Canada'
      WHEN regexp_matches(page, '\.cv/') THEN 'Cape Verde (in Portuguese: Cabo Verde)'
      WHEN regexp_matches(page, '\.cat/') THEN 'Catalonia'
      WHEN regexp_matches(page, '\.ky/') THEN 'Cayman Islands'
      WHEN regexp_matches(page, '\.cf/') THEN 'Central African Republic'
      WHEN regexp_matches(page, '\.td/') THEN 'Chad'
      WHEN regexp_matches(page, '\.cl/') THEN 'Chile'
      WHEN regexp_matches(page, '\.cn/') THEN 'China'
      WHEN regexp_matches(page, '\.cx/') THEN 'Christmas Island'
      WHEN regexp_matches(page, '\.cc/') THEN 'Cocos (Keeling) Islands'
      WHEN regexp_matches(page, '\.co/') THEN 'Colombia'
      WHEN regexp_matches(page, '\.km/') THEN 'Comoros'
      WHEN regexp_matches(page, '\.cd/') THEN 'Congo (Congo-Kinshasa)'
      WHEN regexp_matches(page, '\.cg/') THEN 'Congo (Congo-Brazzaville)'
      WHEN regexp_matches(page, '\.ck/') THEN 'Cook Islands'
      WHEN regexp_matches(page, '\.cr/') THEN 'Costa Rica'
      WHEN regexp_matches(page, '\.ci/') THEN 'Ivory Coast'
      WHEN regexp_matches(page, '\.cu/') THEN 'Cuba'
      WHEN regexp_matches(page, '\.cw/') THEN 'Curaçao'
      WHEN regexp_matches(page, '\.dj/') THEN 'Djibouti'
      WHEN regexp_matches(page, '\.dm/') THEN 'Dominica'
      WHEN regexp_matches(page, '\.do/') THEN 'Dominican Republic'
      WHEN regexp_matches(page, '\.tl/') THEN 'East Timor (Timor-Leste)'
      WHEN regexp_matches(page, '\.tp/') THEN 'East Timor (Timor-Leste)'
      WHEN regexp_matches(page, '\.ec/') THEN 'Ecuador'
      WHEN regexp_matches(page, '\.eg/') THEN 'Egypt'
      WHEN regexp_matches(page, '\.sv/') THEN 'El Salvador'
      WHEN regexp_matches(page, '\.gq/') THEN 'Equatorial Guinea'
      WHEN regexp_matches(page, '\.er/') THEN 'Eritrea'
      WHEN regexp_matches(page, '\.et/') THEN 'Ethiopia'
      WHEN regexp_matches(page, '\.eu/') THEN 'European Union'
      WHEN regexp_matches(page, '\.fk/') THEN 'Falkland Islands'
      WHEN regexp_matches(page, '\.fo/') THEN 'Faeroe Islands'
      WHEN regexp_matches(page, '\.fm/') THEN 'Federated States of Micronesia'
      WHEN regexp_matches(page, '\.fj/') THEN 'Fiji'
      WHEN regexp_matches(page, '\.gf/') THEN 'French Guiana'
      WHEN regexp_matches(page, '\.pf/') THEN 'French Polynesia'
      WHEN regexp_matches(page, '\.tf/') THEN 'French Southern and Antarctic Lands'
      WHEN regexp_matches(page, '\.ga/') THEN 'Gabon'
      WHEN regexp_matches(page, '\.gal/') THEN 'Galicia'
      WHEN regexp_matches(page, '\.gm/') THEN 'Gambia'
      WHEN regexp_matches(page, '\.ps/') THEN 'Gaza'
      WHEN regexp_matches(page, '\.gh/') THEN 'Ghana'
      WHEN regexp_matches(page, '\.gd/') THEN 'Grenada'
      WHEN regexp_matches(page, '\.gp/') THEN 'Guadeloupe'
      WHEN regexp_matches(page, '\.gu/') THEN 'Guam'
      WHEN regexp_matches(page, '\.gt/') THEN 'Guatemala'
      WHEN regexp_matches(page, '\.gg/') THEN 'Guernsey'
      WHEN regexp_matches(page, '\.gn/') THEN 'Guinea'
      WHEN regexp_matches(page, '\.gw/') THEN 'Guinea-Bissau'
      WHEN regexp_matches(page, '\.gy/') THEN 'Guyana'
      WHEN regexp_matches(page, '\.ht/') THEN 'Haiti'
      WHEN regexp_matches(page, '\.hm/') THEN 'Heard Island'
      WHEN regexp_matches(page, '\.hn/') THEN 'Honduras'
      WHEN regexp_matches(page, '\.hk/') THEN 'Hong Kong'
      WHEN regexp_matches(page, '\.(gov|mil)\.in/|\.nic\.in/') THEN 'India'
      WHEN regexp_matches(page, '\.id/') THEN 'Indonesia'
      WHEN regexp_matches(page, '\.ir/') THEN 'Iran'
      WHEN regexp_matches(page, '\.iq/') THEN 'Iraq'
      WHEN regexp_matches(page, '\.il/') THEN 'Israel'
      WHEN regexp_matches(page, '\.it/') THEN 'Italy'
      WHEN regexp_matches(page, '\.jm/') THEN 'Jamaica'
      WHEN regexp_matches(page, '\.jp/') THEN 'Japan'
      WHEN regexp_matches(page, '\.je/') THEN 'Jersey'
      WHEN regexp_matches(page, '\.jo/') THEN 'Jordan'
      WHEN regexp_matches(page, '\.ke/') THEN 'Kenya'
      WHEN regexp_matches(page, '\.ki/') THEN 'Kiribati'
      WHEN regexp_matches(page, '\.kw/') THEN 'Kuwait'
      WHEN regexp_matches(page, '\.kg/') THEN 'Kyrgyzstan'
      WHEN regexp_matches(page, '\.la/') THEN 'Laos'
      WHEN regexp_matches(page, '\.lb/') THEN 'Lebanon'
      WHEN regexp_matches(page, '\.ls/') THEN 'Lesotho'
      WHEN regexp_matches(page, '\.lr/') THEN 'Liberia'
      WHEN regexp_matches(page, '\.ly/') THEN 'Libya'
      WHEN regexp_matches(page, '\.mo/') THEN 'Macau'
      WHEN regexp_matches(page, '\.mg/') THEN 'Madagascar'
      WHEN regexp_matches(page, '\.mw/') THEN 'Malawi'
      WHEN regexp_matches(page, '\.my/') THEN 'Malaysia'
      WHEN regexp_matches(page, '\.mv/') THEN 'Maldives'
      WHEN regexp_matches(page, '\.ml/') THEN 'Mali'
      WHEN regexp_matches(page, '\.mh/') THEN 'Marshall Islands'
      WHEN regexp_matches(page, '\.mq/') THEN 'Martinique'
      WHEN regexp_matches(page, '\.mr/') THEN 'Mauritania'
      WHEN regexp_matches(page, '\.mu/') THEN 'Mauritius'
      WHEN regexp_matches(page, '\.yt/') THEN 'Mayotte'
      WHEN regexp_matches(page, '\.mx/') THEN 'Mexico'
      WHEN regexp_matches(page, '\.mn/') THEN 'Mongolia'
      WHEN regexp_matches(page, '\.ms/') THEN 'Montserrat'
      WHEN regexp_matches(page, '\.ma/') THEN 'Morocco'
      WHEN regexp_matches(page, '\.mz/') THEN 'Mozambique'
      WHEN regexp_matches(page, '\.mm/') THEN 'Myanmar'
      WHEN regexp_matches(page, '\.na/') THEN 'Namibia'
      WHEN regexp_matches(page, '\.nr/') THEN 'Nauru'
      WHEN regexp_matches(page, '\.np/') THEN 'Nepal'
      WHEN regexp_matches(page, '\.nl/') THEN 'Netherlands'
      WHEN regexp_matches(page, '\.nc/') THEN 'New Caledonia'
      WHEN regexp_matches(page, '\.nz/') THEN 'New Zealand'
      WHEN regexp_matches(page, '\.ni/') THEN 'Nicaragua'
      WHEN regexp_matches(page, '\.ne/') THEN 'Niger'
      WHEN regexp_matches(page, '\.ng/') THEN 'Nigeria'
      WHEN regexp_matches(page, '\.nu/') THEN 'Niue'
      WHEN regexp_matches(page, '\.nf/') THEN 'Norfolk Island'
      WHEN regexp_matches(page, '\.kp/') THEN 'North Korea'
      WHEN regexp_matches(page, '\.mp/') THEN 'Northern Mariana Islands'
      WHEN regexp_matches(page, '\.om/') THEN 'Oman'
      WHEN regexp_matches(page, '\.pk/') THEN 'Pakistan'
      WHEN regexp_matches(page, '\.pw/') THEN 'Palau'
      WHEN regexp_matches(page, '\.ps/') THEN 'Palestine'
      WHEN regexp_matches(page, '\.pa/') THEN 'Panama'
      WHEN regexp_matches(page, '\.pg/') THEN 'Papua New Guinea'
      WHEN regexp_matches(page, '\.py/') THEN 'Paraguay'
      WHEN regexp_matches(page, '\.pe/') THEN 'Peru'
      WHEN regexp_matches(page, '\.ph/') THEN 'Philippines'
      WHEN regexp_matches(page, '\.pn/') THEN 'Pitcairn Islands'
      WHEN regexp_matches(page, '\.pr/') THEN 'Puerto Rico'
      WHEN regexp_matches(page, '\.qa/') THEN 'Qatar'
      WHEN regexp_matches(page, '\.rw/') THEN 'Rwanda'
      WHEN regexp_matches(page, '\.re/') THEN 'Réunion Island'
      WHEN regexp_matches(page, '\.sh/') THEN 'Saint Helena'
      WHEN regexp_matches(page, '\.kn/') THEN 'Saint Kitts and Nevis'
      WHEN regexp_matches(page, '\.lc/') THEN 'Saint Lucia'
      WHEN regexp_matches(page, '\.pm/') THEN 'Saint-Pierre and Miquelon'
      WHEN regexp_matches(page, '\.vc/') THEN 'Saint Vincent and the Grenadines'
      WHEN regexp_matches(page, '\.ws/') THEN 'Samoa'
      WHEN regexp_matches(page, '\.st/') THEN 'São Tomé and Príncipe'
      WHEN regexp_matches(page, '\.sa/') THEN 'Saudi Arabia'
      WHEN regexp_matches(page, '\.sn/') THEN 'Senegal'
      WHEN regexp_matches(page, '\.sc/') THEN 'Seychelles'
      WHEN regexp_matches(page, '\.sl/') THEN 'Sierra Leone'
      WHEN regexp_matches(page, '\.sg/') THEN 'Singapore'
      WHEN regexp_matches(page, '\.sx/') THEN 'Sint Maarten'
      WHEN regexp_matches(page, '\.sb/') THEN 'Solomon Islands'
      WHEN regexp_matches(page, '\.so/') THEN 'Somalia'
      WHEN regexp_matches(page, '\.za/') THEN 'South Africa'
      WHEN regexp_matches(page, '\.gs/') THEN 'South Georgia and the South Sandwich Islands'
      WHEN regexp_matches(page, '\.kr/') THEN 'South Korea'
      WHEN regexp_matches(page, '\.ss/') THEN 'South Sudan'
      WHEN regexp_matches(page, '\.es/') THEN 'Spain'
      WHEN regexp_matches(page, '\.lk/') THEN 'Sri Lanka'
      WHEN regexp_matches(page, '\.sd/') THEN 'Sudan'
      WHEN regexp_matches(page, '\.sr/') THEN 'Suriname'
      WHEN regexp_matches(page, '\.sz/') THEN 'Swaziland'
      WHEN regexp_matches(page, '\.se/') THEN 'Sweden'
      WHEN regexp_matches(page, '\.sy/') THEN 'Syria'
      WHEN regexp_matches(page, '\.gov\.tw/|\.taipei/') THEN 'Taiwan'
      WHEN regexp_matches(page, '\.tj/') THEN 'Tajikistan'
      WHEN regexp_matches(page, '\.tz/') THEN 'Tanzania'
      WHEN regexp_matches(page, '\.th/') THEN 'Thailand'
      WHEN regexp_matches(page, '\.tg/') THEN 'Togo'
      WHEN regexp_matches(page, '\.tk/') THEN 'Tokelau'
      WHEN regexp_matches(page, '\.to/') THEN 'Tonga'
      WHEN regexp_matches(page, '\.tt/') THEN 'Trinidad & Tobago'
      WHEN regexp_matches(page, '\.tn/') THEN 'Tunisia'
      WHEN regexp_matches(page, '\.tr/') THEN 'Turkey'
      WHEN regexp_matches(page, '\.tm/') THEN 'Turkmenistan'
      WHEN regexp_matches(page, '\.tc/') THEN 'Turks and Caicos Islands'
      WHEN regexp_matches(page, '\.tv/') THEN 'Tuvalu'
      WHEN regexp_matches(page, '\.ug/') THEN 'Uganda'
      WHEN regexp_matches(page, '\.ua/') THEN 'Ukraine'
      WHEN regexp_matches(page, '\.ae/') THEN 'United Arab Emirates (UAE)'
      WHEN regexp_matches(page, '\.vi/') THEN 'United States Virgin Islands'
      WHEN regexp_matches(page, '\.uy/') THEN 'Uruguay'
      WHEN regexp_matches(page, '\.uz/') THEN 'Uzbekistan'
      WHEN regexp_matches(page, '\.vu/') THEN 'Vanuatu'
      WHEN regexp_matches(page, '\.va/') THEN 'Vatican City'
      WHEN regexp_matches(page, '\.ve/') THEN 'Venezuela'
      WHEN regexp_matches(page, '\.vn/') THEN 'Vietnam'
      WHEN regexp_matches(page, '\.wf/') THEN 'Wallis and Futuna'
      WHEN regexp_matches(page, '\.eh/') THEN 'Western Sahara'
      WHEN regexp_matches(page, '\.ye/') THEN 'Yemen'
      WHEN regexp_matches(page, '\.zm/') THEN 'Zambia'
      WHEN regexp_matches(page, '\.zw/') THEN 'Zimbabwe'

      -- All other .gov defintions will be American
      WHEN regexp_matches(page, '\.(gov|mil)/') THEN 'United States (USA)'

      ELSE 'Other'
    END AS gov_domain,
    performance_score,
    accessibility_score,
    best_practices_score,
    seo_score
  FROM
    score_data
  WHERE
    regexp_matches(
      page, '('
      '\.un\.org/'  -- United Nations and International Organizations
      '|\.worldbank\.org/'
      '|\.undp\.org/'
      '|\.reliefweb\.int/'
      '|\.who\.int/'
      '|\.unfccc\.int/'
      '|\.unccd\.int/'
      '|\.unesco\.org/'

      '|\.europa\.eu/'  -- European Union

      '|\.gov/'  -- US Government
      '|\.mil/'  -- US Military

      '|\.myflorida\.com/' -- Florida

      '|\.(gov|mil|gouv|gob|gub|go|govt|gv|nic|government)\.(taipei|[a-z]{2,3})/' -- Other generic government formats (e.g., gouv.fr, gob.mx, go.jp)

      '|\.gc\.ca/'  -- Canada and provinces
      '|\.canada\.ca/'
      '|\.alberta\.ca/'
      '|\.gov\.ab\.ca/'
      '|\.gov\.bc\.ca/'
      '|\.manitoba\.ca/'
      '|\.gov\.mb\.ca/'
      '|\.gnb\.ca/'
      '|\.gov\.nb\.ca/'
      '|\.gov\.nl\.ca/'
      '|\.novascotia\.ca/'
      '|\.gov\.ns\.ca/'
      '|\.ontario\.ca/'
      '|\.gov\.on\.ca/'
      '|\.gov\.pe\.ca/'
      '|\.quebec\.ca/'
      '|\.gouv\.qc\.ca/'
      '|\.revenuquebec\.ca/'
      '|\.saskatchewan\.ca/'
      '|\.gov\.sk\.ca/'
      '|\.gov\.nt\.ca/'
      '|\.gov\.nu\.ca/'
      '|\.yukon\.ca/'
      '|\.gov\.yk\.ca/'

      '|\.bund\.de/'  -- Germany

      '|\.belgium\.be/'  -- Belgium
      '|\.fgov\.be/'
      '|\.vlaanderen\.be/'
      '|\.wallonie\.be/'
      '|\.brussels\.be/'
      '|\.mil\.be/'

      '|\.gov\.se/'  -- Sweden
      '|\.1177\.se/'
      '|\.funktionstjanster\.se/'
      '|\.hemnet\.se/'
      '|\.smhi\.se/'
      '|\.sverigesradio\.se/'
      '|\.klart\.se/'
      '|\.bankid\.com/'
      '|\.synonymer\.se/'
      '|\.arbetsformedlingen\.se/'
      '|\.skatteverket\.se/'
      '|\.schoolsoft\.se/'
      '|\.postnord\.se/'
      '|\.grandid\.com/'
      '|\.viaplay\.se/'
      '|\.skola24\.se/'
      '|\.forsakringskassan\.se/'
      '|\.vklass\.se/'
      '|\.sl\.se/'
      '|\.familjeliv\.se/'

      '|\.regjeringen\.no/'  -- Norway
      '|\.stortinget\.no/'
      '|\.nav\.no/'
      '|\.helsenorge\.no/'
      '|\.udir\.no/'
      '|\.udi\.no/'
      '|\.politi\.no/'
      '|\.nve\.no/'
      '|\.ssb\.no/'
      '|\.miljodirektoratet\.no/'
      '|\.arbeidstilsynet\.no/'
      '|\.forsvaret\.no/'
      '|\.skatteetaten\.no/'
      '|\.brreg\.no/'
      '|\.vegvesen\.no/'
      '|\.mattilsynet\.no/'
      '|\.lovdata\.no/'
      '|\.altinn\.no/'
      '|\.nkom\.no/'
      '|\.fhi\.no/'
      '|\.dsa\.no/'
      '|\.kystverket\.no/'
      '|\.bufdir\.no/'
      '|\.nupi\.no/'

      '|\.gov\.gl/' -- Greenland
      '|\.naalakkersuisut\.gl/'
      '|\.stat\.gl/'
      '|\.oqaasileriffik\.gl/'
      '|\.sullissivik\.gl/'
      '|\.sisimiut\.gl/'
      '|\.kalaallitnunaata\.gl/'
      '|\.inatsisartut\.gl/'
      '|\.politi\.gl/'
      '|\.visitgreenland\.gl/'
      '|\.energitjenesten\.gl/'
      '|\.nusuka\.gl/'
      '|\.telepost\.gl/'
      '|\.kujalleq\.gl/'
      '|\.sermersooq\.gl/'
      '|\.aviisi\.gl/'
      '|\.anjuma\.gl/'
      '|\.kni\.gl/'
      '|\.greenlandinstitute\.gl/'
      '|\.mhs\.gl/'
      '|\.iluarsartuiffik\.gl/'
      '|\.royalgroenland\.gl/'
      '|\.gux\.gl/'
      '|\.univiseyisarti\.gl/'
      '|\.arcticcommand\.gl/'

      '|\.valtioneuvosto\.fi/'  -- Finland
      '|\.minedu\.fi/'
      '|\.formin\.fi/'
      '|\.intermin\.fi/'
      '|\.suomi\.fi/'
      '|\.ym\.fi/'
      '|\.stm\.fi/'
      '|\.tem\.fi/'
      '|\.lvm\.fi/'
      '|\.mmm\.fi/'
      '|\.okm\.fi/'
      '|\.vm\.fi/'
      '|\.defmin\.fi/'
      '|\.oikeusministerio\.fi/'
      '|\.um\.fi/'
      '|\.vero\.fi/'
      '|\.kela\.fi/'

      '|\.lrv\.lt/'  -- Lithuania
      '|\.uzt\.lt/'
      '|\.migracija\.lt/'
      '|\.kam\.lt/'
      '|\.lrs\.lt/'
      '|\.urm\.lt/'

      '|\.riik\.ee/'  -- Estonia
      '|\.riigiteataja\.ee/'
      '|\.eesti\.ee/'
      '|\.valitsus\.ee/'

      '|\.admin\.ch/'  -- Switzerland

      '|\.seg-social\.es/'  -- Spain
      '|\.ine\.es/'
      '|\.boe\.es/'

      '|\.ft\.dk/'  -- Denmark
      '|\.nemkonto\.dk/'
      '|\.nemlog-in\.dk/'
      '|\.mitid\.dk/'
      '|\.digst\.dk/'
      '|\.sikkerdigital\.dk/'
      '|\.forsvaret\.dk/'
      '|\.skat\.dk/'
      '|\.stps\.dk/'
      '|\.ufm\.dk/'
      '|\.urm\.dk/'
      '|\.uvm\.dk/'
      '|\.politi\.dk/'
      '|\.dataetiskraad\.dk/'
      '|\.at\.dk/'
      '|\.kum\.dk/'

      '|\.govvrn\.ru/' -- Russia

      '|\.public\.lu/'  -- Luxembourg
      '|\.etat\.lu/'

      '|\.governo\.it/'  -- Italy

      '|\.overheid\.nl/'  -- Netherlands
      '|\.mijnoverheid\.nl/'

      '|\.govern\.ad/'  -- Andorra
      '|\.exteriors\.ad/'
      '|\.consellgeneral\.ad/'

      ')'
    )
)

SELECT
  gov_domain,
  AVG(performance_score) AS average_performance_score,
  AVG(accessibility_score) AS average_accessibility_score,
  AVG(best_practices_score) AS average_best_practices_score,
  AVG(seo_score) AS average_seo_score,
  COUNT(0) AS total_domains
FROM
  domain_scores
GROUP BY
  gov_domain
ORDER BY
  average_accessibility_score DESC;
