create table pivot_downloads as
SELECT
    day,
    SUM(total_downloads) AS total_downloads,
    SUM(CASE WHEN minor_version = '0.1' THEN total_downloads ELSE 0 END) AS "0.1",
    SUM(CASE WHEN minor_version = '0.2' THEN total_downloads ELSE 0 END) AS "0.2",
    SUM(CASE WHEN minor_version = '0.3' THEN total_downloads ELSE 0 END) AS "0.3",
    SUM(CASE WHEN minor_version = '0.4' THEN total_downloads ELSE 0 END) AS "0.4",
    SUM(CASE WHEN minor_version = '0.5' THEN total_downloads ELSE 0 END) AS "0.5",
    SUM(CASE WHEN minor_version = '0.6' THEN total_downloads ELSE 0 END) AS "0.6",
    SUM(CASE WHEN minor_version = '0.7' THEN total_downloads ELSE 0 END) AS "0.7",
    SUM(CASE WHEN minor_version = '0.8' THEN total_downloads ELSE 0 END) AS "0.8",
    SUM(CASE WHEN minor_version = '1.0' THEN total_downloads ELSE 0 END) AS "1.0",
    SUM(CASE WHEN minor_version = '1.1' THEN total_downloads ELSE 0 END) AS "1.1",
    SUM(CASE WHEN minor_version = '1.2' THEN total_downloads ELSE 0 END) AS "1.2",
    SUM(CASE WHEN minor_version = '1.3' THEN total_downloads ELSE 0 END) AS "1.3",
    SUM(CASE WHEN minor_version = '1.4' THEN total_downloads ELSE 0 END) AS "1.4",
    SUM(CASE WHEN minor_version = '1.5' THEN total_downloads ELSE 0 END) AS "1.5",
    SUM(CASE WHEN minor_version = '1.6' THEN total_downloads ELSE 0 END) AS "1.6",
    SUM(CASE WHEN minor_version = '1.7' THEN total_downloads ELSE 0 END) AS "1.7",
    SUM(CASE WHEN minor_version = '1.8' THEN total_downloads ELSE 0 END) AS "1.8",
    SUM(CASE WHEN minor_version = '1.9' THEN total_downloads ELSE 0 END) AS "1.9",
    SUM(CASE WHEN minor_version = '1.10' THEN total_downloads ELSE 0 END) AS "1.10",
    SUM(CASE WHEN minor_version = '1.11' THEN total_downloads ELSE 0 END) AS "1.11",
    SUM(CASE WHEN minor_version = '1.12' THEN total_downloads ELSE 0 END) AS "1.12",
    SUM(CASE WHEN minor_version = '1.13' THEN total_downloads ELSE 0 END) AS "1.13",
    SUM(CASE WHEN minor_version = '2.0' THEN total_downloads ELSE 0 END) AS "2.0",
    SUM(CASE WHEN minor_version = '2.1' THEN total_downloads ELSE 0 END) AS "2.1",
    SUM(CASE WHEN minor_version = '2.2' THEN total_downloads ELSE 0 END) AS "2.2",
    SUM(CASE WHEN minor_version = '2.3' THEN total_downloads ELSE 0 END) AS "2.3",
    SUM(CASE WHEN minor_version = '2.4' THEN total_downloads ELSE 0 END) AS "2.4",
    SUM(CASE WHEN minor_version = '2.5' THEN total_downloads ELSE 0 END) AS "2.5",
    SUM(CASE WHEN minor_version = '2.6' THEN total_downloads ELSE 0 END) AS "2.6",
    SUM(CASE WHEN minor_version = '2.7' THEN total_downloads ELSE 0 END) AS "2.7",
    SUM(CASE WHEN minor_version = '2.8' THEN total_downloads ELSE 0 END) AS "2.8",
    SUM(CASE WHEN minor_version = '2.9' THEN total_downloads ELSE 0 END) AS "2.9",
    SUM(CASE WHEN minor_version = '2.10' THEN total_downloads ELSE 0 END) AS "2.10",
    SUM(CASE WHEN minor_version = '2.11' THEN total_downloads ELSE 0 END) AS "2.11",
    SUM(CASE WHEN minor_version = '2.12' THEN total_downloads ELSE 0 END) AS "2.12",
    SUM(CASE WHEN minor_version = '2.13' THEN total_downloads ELSE 0 END) AS "2.13",
    SUM(CASE WHEN minor_version = '2.14' THEN total_downloads ELSE 0 END) AS "2.14",
    SUM(CASE WHEN minor_version = '2.15' THEN total_downloads ELSE 0 END) AS "2.15",
    SUM(CASE WHEN minor_version = '2.16' THEN total_downloads ELSE 0 END) AS "2.16",
    SUM(CASE WHEN minor_version = '3.0' THEN total_downloads ELSE 0 END) AS "3.0",
    SUM(CASE WHEN minor_version = '4.0' THEN total_downloads ELSE 0 END) AS "4.0",
    SUM(CASE WHEN minor_version = '4.1' THEN total_downloads ELSE 0 END) AS "4.1",
    SUM(CASE WHEN minor_version = '4.2' THEN total_downloads ELSE 0 END) AS "4.2",
    SUM(CASE WHEN minor_version = '5.0' THEN total_downloads ELSE 0 END) AS "5.0",
    SUM(CASE WHEN minor_version = '5.1' THEN total_downloads ELSE 0 END) AS "5.1",
    SUM(CASE WHEN minor_version = '5.2' THEN total_downloads ELSE 0 END) AS "5.2",
    SUM(CASE WHEN minor_version = '6.0' THEN total_downloads ELSE 0 END) AS "6.0",
    SUM(CASE WHEN minor_version = '6.1' THEN total_downloads ELSE 0 END) AS "6.1",
    SUM(CASE WHEN minor_version = '6.2' THEN total_downloads ELSE 0 END) AS "6.2",
    SUM(CASE WHEN minor_version = '6.3' THEN total_downloads ELSE 0 END) AS "6.3",
    SUM(CASE WHEN minor_version = '6.4' THEN total_downloads ELSE 0 END) AS "6.4",
FROM feature_versions
GROUP BY day
ORDER BY day;
